In [1]:
import torch
import numpy as np

In [2]:
# 데이터로부터 직접 텐서 초기화 
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

# numpy 배열로부터 텐서 초기화
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [6]:
# 다른 텐서로부터 생성하기
# 명시적으로 재정의하지 않는다면 인자로 주어진 텐서의 속상, 자료형은 유지됨

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Rand Tensor: \n {x_rand}")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])
Rand Tensor: 
 tensor([[0.5012, 0.5767],
        [0.0467, 0.3506]])


In [7]:
# 무작위 또는 상수 값 사용
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.rand(shape)
zeros_tensor = torch.zeros(shape)

print(f"Rand Tensor {rand_tensor}")
print(f"Ones Tensor {ones_tensor}")
print(f"Zero Tensor {zeros_tensor}")

Rand Tensor tensor([[0.5907, 0.9671, 0.8557],
        [0.3065, 0.7228, 0.7051]])
Ones Tensor tensor([[0.4295, 0.9431, 0.1199],
        [0.5259, 0.2497, 0.8640]])
Zero Tensor tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# Tensor 연산
# Transposing, Indexing, Slicing, 수학 계산, 선형 대수, 임의 샘플링의 연산은 GPU에서 실행 가능
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [11]:
# Numpy 식의 표준 인덱싱 및 슬라이싱
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# 1번째 열 0으로 만들기
tensor[:, 1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# 텐서 합치기 torch.cat을 통해 주어진 차원에 따라 일련의 텐서 연결
# 유사하게 torch.stack도 존재

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)